// Code generated by gogen.go; DO NOT EDIT.

package data

import "cloud.google.com/go/firestore"

const (
	AppConfig_XSRFKey                        = "xsrfKey"
	AppConfig_HMACKeys                       = "hmacKeys"
	AppConfig_AdminIDs                       = "adminIDs"
	AppConfig_LoginClient                    = "loginClient"
	AppConfig_PlanningSheetURL               = "planningSheetURL"
	AppConfig_PlanningSheetServiceAccountKey = "planningSheetServiceAccountKey"
)

const (
	Class_Number           = "number"
	Class_Length           = "length"
	Class_Responsibility   = "responsibility"
	Class_New              = "new"
	Class_Title            = "title"
	Class_TitleNotes       = "titleNotes"
	Class_Description      = "description"
	Class_Programs         = "programs"
	Class_Capacity         = "capacity"
	Class_Location         = "location"
	Class_SpreadsheetRow   = "spreadsheetRow"
	Class_InstructorNames  = "instructorNames"
	Class_InstructorEmails = "instructorEmails"
	Class_EvaluationCodes  = "evaluationCodes"
	Class_AccessToken      = "accessToken"
	Class_DKDirty          = "dkDirty"
)

const (
	Conference_Lunches = "lunches"
	Conference_Date    = "Date"
)

const (
	Participant_RegistrationNumber  = "registrationNumber"
	Participant_FirstName           = "firstName"
	Participant_LastName            = "lastName"
	Participant_Nickname            = "nickname"
	Participant_Suffix              = "suffix"
	Participant_Staff               = "staff"
	Participant_Youth               = "youth"
	Participant_Phone               = "phone"
	Participant_Email               = "email"
	Participant_Address             = "address"
	Participant_City                = "city"
	Participant_State               = "state"
	Participant_Zip                 = "zip"
	Participant_StaffRole           = "staffRole"
	Participant_Council             = "council"
	Participant_District            = "district"
	Participant_UnitType            = "unitType"
	Participant_UnitNumber          = "unitNumber"
	Participant_DietaryRestrictions = "dietaryRestrictions"
	Participant_Marketing           = "marketing"
	Participant_ScoutingYears       = "scoutingYears"
	Participant_ShowQRCode          = "showQRCode"
	Participant_BSANumber           = "bsaNumber"
	Participant_Classes             = "classes"
	Participant_StaffDescription    = "staffDescription"
	Participant_Notes               = "notes"
	Participant_NoShow              = "noShow"
)

var ClassMerge_Sheet = firestore.Merge(firestore.FieldPath{
	Class_Number,
	Class_Length,
	Class_Responsibility,
	Class_New,
	Class_Title,
	Class_TitleNotes,
	Class_Description,
	Class_Programs,
	Class_Capacity,
	Class_Location,
	Class_SpreadsheetRow,
	Class_InstructorNames,
	Class_InstructorEmails,
	Class_EvaluationCodes,
	Class_AccessToken,
})

var ParticipantMerge_DK = firestore.Merge(firestore.FieldPath{
	Participant_RegistrationNumber,
	Participant_FirstName,
	Participant_LastName,
	Participant_Nickname,
	Participant_Suffix,
	Participant_Staff,
	Participant_Youth,
	Participant_Phone,
	Participant_Email,
	Participant_Address,
	Participant_City,
	Participant_State,
	Participant_Zip,
	Participant_StaffRole,
	Participant_Council,
	Participant_District,
	Participant_UnitType,
	Participant_UnitNumber,
	Participant_DietaryRestrictions,
	Participant_Marketing,
	Participant_ScoutingYears,
	Participant_ShowQRCode,
	Participant_BSANumber,
	Participant_Classes,
	Participant_StaffDescription,
})
