// Code generated by gogen.go; DO NOT EDIT.

package model

const (
	AppConfig_AdminIDs                       = "adminIDs"
	AppConfig_HMACKeys                       = "hmacKeys"
	AppConfig_LoginClient                    = "loginClient"
	AppConfig_PlanningSheetServiceAccountKey = "planningSheetServiceAccountKey"
	AppConfig_PlanningSheetURL               = "planningSheetURL"
	AppConfig_StaffIDs                       = "staffIDs"
	AppConfig_Timestamp                      = "timestamp"
	AppConfig_XSRFKey                        = "xsrfKey"
)
