// Code generated by gogen.go; DO NOT EDIT.

package model

const (
	Conference_CatalogStatusMessage = "catalogStatusMessage"
	Conference_Lunches              = "lunches"
	Conference_NoClassDescription   = "noClassDescription"
	Conference_OABanquetDescription = "oaBanquetDescription"
	Conference_OABanquetLocation    = "oaBanquetLocation"
	Conference_OpeningLocation      = "openingLocation"
	Conference_RegistrationURL      = "registrationURL"
	Conference_StaffIDs             = "staffIDs"
)
