// Code generated by gogen.go; DO NOT EDIT.

package model

const (
	AppConfig_AdminIDs                       = "adminIDs"
	AppConfig_ClassesSheetURL                = "classesSheetURL"
	AppConfig_HMACKeys                       = "hmacKeys"
	AppConfig_LoginClient                    = "loginClient"
	AppConfig_PlanningSheetServiceAccountKey = "planningSheetServiceAccountKey"
	AppConfig_StaffIDs                       = "staffIDs"
	AppConfig_SuggestedSchedulesSheetURL     = "suggestedScheduleSheetURL"
	AppConfig_XSRFKey                        = "xsrfKey"
)
