// Code generated by gogen.go; DO NOT EDIT.

package model

const (
	Conference_Day                = "day"
	Conference_Lunches            = "lunches"
	Conference_Month              = "month"
	Conference_RegistrationURL    = "registrationURL"
	Conference_SuggestedSchedules = "SuggestedSchedules"
	Conference_Year               = "year"
)
