// Code generated by gogen.go; DO NOT EDIT.

package model

const (
	Conference_Day                = "day"
	Conference_LastUpdateTime     = "lastUpdateTime"
	Conference_Lunches            = "lunches"
	Conference_Month              = "month"
	Conference_SuggestedSchedules = "suggestedSchedules"
	Conference_Year               = "year"
)
