runtime: go112
default_expiration: "2d"
main: ./seaptc

handlers:
- url: /favicon\.ico
  static_files: assets/static/favicon.ico
  upload: assets/static/favicon.ico

- url: /robots\.txt
  static_files: assets/static/robots.txt
  upload: assets/static/robots.txt

- url: /static/
  static_dir: assets/static

- url: /.*
  secure: always
  script: auto
